# Generated by Django 4.0.3 on 2022-07-12 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passwordmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttagmap',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_map_account', to='passwordmanager.userownaccount'),
        ),
        migrations.AlterField(
            model_name='accounttagmap',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_map', to='passwordmanager.tag'),
        ),
        migrations.AlterField(
            model_name='accounttagmap',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_map_user', to='passwordmanager.user'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userownaccount',
            name='alias',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userownaccount',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userownaccount',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userownaccount',
            name='sitename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userownaccount',
            name='siteurl',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userownaccount',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_account', to='passwordmanager.user'),
        ),
        migrations.AlterField(
            model_name='userownaccount',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
